name: zed_events
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2 # Updated to the latest version
  shared_preferences: ^2.5.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides: # Add this section to force specific versions
  characters: ^1.4.0
  clock: ^1.1.2
  collection: ^1.19.1
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  async: ^2.13.0
  boolean_selector: ^2.1.2
  fake_async: ^1.3.3
  matcher: ^0.12.17
  source_span: ^1.10.1
  stack_trace: ^1.12.1
  stream_channel: ^2.1.4
  string_scanner: ^1.4.1
  term_glyph: ^1.2.2
  test_api: ^0.7.4
  vm_service: ^15.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700